#!/bin/bash
read -p "Enter the a  values:-" a 
read -p " enter the b value:-" b
read -p " enter the c value:-" c

if [   $a -gt $b ] && [ $a -gt $c ]
then
  echo " $a is greater than  $b and $c"

elif [   $b -gt $a ] && [ $b -gt $c ]
then

    echo " $b is greater than $a and $c"

else
     echo"$c is greater"
 
fi
