#!/bin/bash

read -p " enter the number a:-" a

if [  $a -gt 0 ] 
then 
 echo " $a is postive number "

elif [ $a -lt 0  ]
then
 echo "  $a is negative number "

else 
 echo " the number is zero"

fi
